#!/usr/bin/env bash
# Copyright 2026 The Lusoris Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# scripts/merge-config.sh — Composable KConfig Fragment Merger
# Complies with NASA/JPL Power of 10: functions <= 60 lines, checked returns.
set -euo pipefail

ARCH="x86_64"
OUTPUT_FILE=""
DRY_RUN="false"
declare -a EXTRA_FRAGMENTS=()

show_usage() {
  cat <<'EOF'
Usage: merge-config.sh [options] [extra_fragments...]
Options:
  --arch=<arch>        Target architecture (x86_64, arm64, riscv64) [default: x86_64]
  --output=<path>      Output path for merged .config [default: output/.config-<arch>]
  --dry-run            Simulate configuration merge without writing target file
  -h, --help           Show this help message
EOF
}

parse_arguments() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --arch=*)
        ARCH="${1#*=}"
        shift
        ;;
      --output=*)
        OUTPUT_FILE="${1#*=}"
        shift
        ;;
      --dry-run)
        DRY_RUN="true"
        shift
        ;;
      -h|--help)
        show_usage
        exit 0
        ;;
      *)
        EXTRA_FRAGMENTS+=("$1")
        shift
        ;;
    esac
  done
}

validate_environment() {
  local valid_archs=("x86_64" "arm64" "riscv64")
  local arch_valid="false"
  for a in "${valid_archs[@]}"; do
    if [[ "${a}" == "${ARCH}" ]]; then
      arch_valid="true"
      break
    fi
  done
  if [[ "${arch_valid}" != "true" ]]; then
    echo "Error: Unsupported target architecture: ${ARCH}" >&2
    return 1
  fi

  if [[ ! -f "kconfig/${ARCH}.config" ]]; then
    echo "Error: Architecture fragment kconfig/${ARCH}.config not found" >&2
    return 1
  fi
  if [[ ! -f "kconfig/security-hardened.config" ]]; then
    echo "Error: Security baseline kconfig/security-hardened.config not found" >&2
    return 1
  fi
}

merge_fragments() {
  local target_out="${1}"
  local tmp_merged
  tmp_merged="$(mktemp)"

  {
    echo "# Generated by nucleus merge-config.sh"
    echo "# Target Architecture: ${ARCH}"
    echo "# Timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo ""
  } > "${tmp_merged}"

  # Merge security baseline first, then arch config, then extras
  local -a sources=("kconfig/security-hardened.config" "kconfig/${ARCH}.config")
  for extra in "${EXTRA_FRAGMENTS[@]}"; do
    if [[ -f "${extra}" ]]; then
      sources+=("${extra}")
    fi
  done

  for src in "${sources[@]}"; do
    echo "==> Merging fragment: ${src}"
    grep -v '^[[:space:]]*#' "${src}" | grep -v '^[[:space:]]*$' >> "${tmp_merged}" || true
  done

  # Deduplicate configuration keys keeping last occurrence
  mkdir -p "$(dirname "${target_out}")"
  awk -F'=' '{if ($1 ~ /^CONFIG_/) {lines[$1]=$0} else {print $0}} END {for (k in lines) print lines[k]}' \
    "${tmp_merged}" | sort > "${target_out}"
  rm -f "${tmp_merged}"
}

verify_security_symbols() {
  local config_path="${1}"
  local -a mandatory_symbols=(
    "CONFIG_STRICT_KERNEL_RWX=y"
    "CONFIG_STACKPROTECTOR_STRONG=y"
    "CONFIG_RANDOMIZE_BASE=y"
    "CONFIG_VMAP_STACK=y"
    "CONFIG_SLAB_FREELIST_HARDENED=y"
  )

  for sym in "${mandatory_symbols[@]}"; do
    if ! grep -qF "${sym}" "${config_path}"; then
      echo "Error: Mandatory security symbol '${sym}' missing from merged config" >&2
      return 1
    fi
  done
  echo "    ✓ Security baseline symbols verified in ${config_path}"
}

main() {
  parse_arguments "$@"
  validate_environment

  if [[ -z "${OUTPUT_FILE}" ]]; then
    OUTPUT_FILE="output/.config-${ARCH}"
  fi

  echo "==> Starting KConfig merge for architecture '${ARCH}'..."
  if [[ "${DRY_RUN}" == "true" ]]; then
    local tmp_check
    tmp_check="$(mktemp)"
    merge_fragments "${tmp_check}"
    verify_security_symbols "${tmp_check}"
    rm -f "${tmp_check}"
    echo "    ✓ [DRY-RUN] KConfig merge and validation succeeded."
    return 0
  fi

  merge_fragments "${OUTPUT_FILE}"
  verify_security_symbols "${OUTPUT_FILE}"
  echo "==> Successfully written merged configuration to ${OUTPUT_FILE}"
}

main "$@"
